# -*- coding: utf-8 -*-
"""LOB_Reconstruction_Optimal_Execution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16V3rF7iaqcDw7PWf8B0kNddtUl1mYdwJ

# Limit Order Book Reconstruction & Optimal Execution Engine

**Author:** Jacky
**Level:** Institutional
**Categories:** Market Microstructure · Algorithmic Trading

This notebook builds, from first principles, a price-time-priority limit
order book (LOB) matching engine, reconstructs book state from a synthetic
tick-level event stream, estimates core market microstructure metrics, and
implements two canonical institutional execution models:

1. **Almgren-Chriss (2000/2001)** — optimal execution / implementation
   shortfall minimization.
2. **Avellaneda-Stoikov (2008)** — inventory-aware market making.

> **Data note:** Genuine Level-2 tick data is not available on free-tier
> market data APIs. This notebook uses a calibrated synthetic order-flow
> simulator as the primary data source (Section 2), with an optional loader
> for real **LOBSTER** sample data (Section 2B) if you have downloaded it
> from lobsterdata.com. Every downstream section (metrics, execution models)
> operates identically on either data source.

## 1. Setup & Imports
"""

# ---------------------------------------------------------------------------
# 1. SETUP & IMPORTS
# ---------------------------------------------------------------------------
# Uncomment the line below if running in a fresh Colab runtime:
# !pip install numpy pandas scipy matplotlib -q

import warnings
from collections import deque

import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['axes.grid'] = True
plt.rcParams['grid.alpha'] = 0.3
pd.set_option('display.float_format', lambda x: f'{x:,.6f}')

print("Environment ready.")
print("numpy:", np.__version__, "| pandas:", pd.__version__)

"""## 2. Configuration

All simulation, execution, and market-making parameters are centralized here
so the notebook can be re-run under different market regimes without hunting
through code cells.

"""

# ---------------------------------------------------------------------------
# 2. GLOBAL CONFIGURATION
# ---------------------------------------------------------------------------
CONFIG = {
    # --- Synthetic order-flow simulator ---
    'sim': {
        'initial_price': 100.00,
        'tick_size': 0.01,
        'num_levels': 8,
        'limit_rate': 3.0,       # limit order arrivals per unit time
        'market_rate': 1.6,      # market order arrivals per unit time
        'cancel_rate': 2.2,      # cancellation events per unit time
        'mean_limit_size': 40,
        'mean_market_size': 35,
        'orders_per_level': 2,   # bootstrap liquidity depth per level
        'bootstrap_size': 30,
        'seed': 11,
        'duration': 1500.0,      # total simulated time units
        'num_levels_snapshot': 5,
    },
    # --- Almgren-Chriss optimal execution ---
    'ac': {
        'X': 100_000,          # shares to liquidate
        'T': 1.0,              # execution horizon (1 trading day, normalized)
        'N': 20,               # number of discrete trading intervals
        'sigma': 0.30,         # daily volatility (price units)
        'eta': 2.5e-6,         # temporary impact coefficient
        'gamma': 2.5e-7,       # permanent impact coefficient
        'arrival_price': 50.0,
        'lam_showcase': 5e-5,  # illustrative risk-aversion level for trajectory plot
    },
    # --- Avellaneda-Stoikov market making ---
    'as_mm': {
        'S0': 100.0,
        'T': 1.0,
        'n_steps': 2000,
        'sigma': 2.0,
        'k': 1.5,      # order-arrival decay parameter
        'A': 140.0,    # order-arrival base intensity
        'seed': 5,
        'gamma_low': 0.1,
        'gamma_high': 1.0,
        'naive_half_spread': 0.5,
    },
}

print("Configuration loaded:", list(CONFIG.keys()))

"""## 2A. Synthetic Order-Flow Generator

New limit orders are placed relative to the **live, current** mid-price of
the book (not a fixed anchor). This is what makes price evolve endogenously
from order-flow imbalance, rather than mean-reverting artificially to an
arbitrary constant.

"""

# ---------------------------------------------------------------------------
# 2A. SYNTHETIC ORDER-FLOW GENERATOR (data source #1 -- always available)
# ---------------------------------------------------------------------------
class LimitOrderBook:
    """Price-time priority limit order book (single-instrument matching engine)."""

    def __init__(self):
        self.bids = {}          # price -> deque([order_id, size], ...)
        self.asks = {}          # price -> deque([order_id, size], ...)
        self.order_index = {}   # order_id -> (side, price)
        self.trade_log = []     # (timestamp, price, size, aggressor_side)
        self.unfilled_market_shares = 0   # diagnostic: liquidity shortfall counter
        self.unfilled_market_events = 0

    def add_limit_order(self, order_id, side, price, size, timestamp):
        """
        Add a limit order, first checking whether it CROSSES the book (a
        'marketable limit order'). Real exchanges match crossing limit
        orders immediately rather than resting them -- skipping this check
        is a common implementation bug that produces an impossible crossed
        book (best_bid > best_ask).
        """
        remaining = size
        if side == 'BUY':
            while remaining > 0 and self.asks and min(self.asks.keys()) <= price:
                best_ask = min(self.asks.keys())
                dq = self.asks[best_ask]
                while dq and remaining > 0:
                    oid, sz = dq[0]
                    fill_qty = min(sz, remaining)
                    self.trade_log.append((timestamp, best_ask, fill_qty, 'BUY'))
                    remaining -= fill_qty
                    if fill_qty == sz:
                        dq.popleft()
                        self.order_index.pop(oid, None)
                    else:
                        dq[0][1] -= fill_qty
                if not dq:
                    del self.asks[best_ask]
            if remaining > 0:
                self.bids.setdefault(price, deque()).append([order_id, remaining])
                self.order_index[order_id] = ('BUY', price)
        else:
            while remaining > 0 and self.bids and max(self.bids.keys()) >= price:
                best_bid = max(self.bids.keys())
                dq = self.bids[best_bid]
                while dq and remaining > 0:
                    oid, sz = dq[0]
                    fill_qty = min(sz, remaining)
                    self.trade_log.append((timestamp, best_bid, fill_qty, 'SELL'))
                    remaining -= fill_qty
                    if fill_qty == sz:
                        dq.popleft()
                        self.order_index.pop(oid, None)
                    else:
                        dq[0][1] -= fill_qty
                if not dq:
                    del self.bids[best_bid]
            if remaining > 0:
                self.asks.setdefault(price, deque()).append([order_id, remaining])
                self.order_index[order_id] = ('SELL', price)

    def cancel_order(self, order_id):
        info = self.order_index.pop(order_id, None)
        if info is None:
            return False  # already filled or cancelled -- not an error
        side, price = info
        book = self.bids if side == 'BUY' else self.asks
        dq = book.get(price)
        if not dq:
            return False
        for i, (oid, _sz) in enumerate(dq):
            if oid == order_id:
                del dq[i]
                break
        if not dq:
            del book[price]
        return True

    def execute_market_order(self, side, size, timestamp):
        book = self.asks if side == 'BUY' else self.bids
        remaining = size
        fills = []
        levels = sorted(book.keys()) if side == 'BUY' else sorted(book.keys(), reverse=True)
        for price in levels:
            if remaining <= 0:
                break
            dq = book[price]
            while dq and remaining > 0:
                oid, sz = dq[0]
                fill_qty = min(sz, remaining)
                fills.append((timestamp, price, fill_qty, side))
                remaining -= fill_qty
                if fill_qty == sz:
                    dq.popleft()
                    self.order_index.pop(oid, None)
                else:
                    dq[0][1] -= fill_qty
            if not dq:
                del book[price]
        self.trade_log.extend(fills)
        if remaining > 0:
            # Market order larger than total resting liquidity on this side.
            # In a real venue this would trigger a halt / reject; here we
            # track it as an aggregate diagnostic rather than warning on
            # every occurrence (which would flood output at realistic
            # order-flow rates).
            self.unfilled_market_shares += remaining
            self.unfilled_market_events += 1
        return fills, remaining

    def best_bid(self):
        return max(self.bids) if self.bids else np.nan

    def best_ask(self):
        return min(self.asks) if self.asks else np.nan

    def mid_price(self):
        bb, ba = self.best_bid(), self.best_ask()
        return np.nan if (np.isnan(bb) or np.isnan(ba)) else 0.5 * (bb + ba)

    def spread(self):
        bb, ba = self.best_bid(), self.best_ask()
        return np.nan if (np.isnan(bb) or np.isnan(ba)) else ba - bb

    def depth_snapshot(self, num_levels=5):
        bid_levels = sorted(self.bids.keys(), reverse=True)[:num_levels]
        ask_levels = sorted(self.asks.keys())[:num_levels]
        bid_sizes = [sum(sz for _, sz in self.bids[p]) for p in bid_levels]
        ask_sizes = [sum(sz for _, sz in self.asks[p]) for p in ask_levels]
        return bid_levels, bid_sizes, ask_levels, ask_sizes


class LOBSimulator:
    """
    Integrated synthetic order-flow generator + matching engine. Order
    arrivals follow independent Poisson processes (limit adds, market
    orders, cancellations); new limit orders are placed relative to the
    CURRENT live mid-price so price evolves endogenously from order-flow
    imbalance rather than mean-reverting to a fixed anchor.
    """

    def __init__(self, initial_price=100.00, tick_size=0.01, num_levels=8,
                 limit_rate=3.0, market_rate=1.6, cancel_rate=2.2,
                 mean_limit_size=40, mean_market_size=35,
                 orders_per_level=2, bootstrap_size=30, seed=42):
        if min(limit_rate, market_rate, cancel_rate) < 0:
            raise ValueError("Arrival rates must be non-negative.")
        if tick_size <= 0 or num_levels < 1:
            raise ValueError("tick_size must be positive and num_levels >= 1.")

        self.initial_price = initial_price
        self.tick_size = tick_size
        self.num_levels = num_levels
        self.limit_rate = limit_rate
        self.market_rate = market_rate
        self.cancel_rate = cancel_rate
        self.mean_limit_size = mean_limit_size
        self.mean_market_size = mean_market_size
        self.orders_per_level = orders_per_level
        self.bootstrap_size = bootstrap_size
        self.rng = np.random.default_rng(seed)
        self._order_counter = 0
        self.lob = LimitOrderBook()
        self._bootstrap()

    def _new_id(self):
        self._order_counter += 1
        return self._order_counter

    def _bootstrap(self):
        """Seed the book with initial resting liquidity so it is never empty."""
        for lvl in range(self.num_levels):
            offset = (lvl + 1) * self.tick_size
            bid_px = round(self.initial_price - offset, 2)
            ask_px = round(self.initial_price + offset, 2)
            for _ in range(self.orders_per_level):
                size = max(1, int(self.rng.lognormal(np.log(self.bootstrap_size), 0.4)))
                self.lob.add_limit_order(self._new_id(), 'BUY', bid_px, size, 0.0)
                size = max(1, int(self.rng.lognormal(np.log(self.bootstrap_size), 0.4)))
                self.lob.add_limit_order(self._new_id(), 'SELL', ask_px, size, 0.0)

    def _reference_price(self):
        m = self.lob.mid_price()
        return m if not np.isnan(m) else self.initial_price

    def run(self, duration=500.0, num_levels_snapshot=5, snapshot_every=1):
        """Run the simulation and return (snapshots_df, trades_df, events_df)."""
        total_rate = self.limit_rate + self.market_rate + self.cancel_rate
        if total_rate <= 0:
            raise ValueError("Total event rate must be positive.")

        t = 0.0
        snapshots, event_log = [], []
        n_events = 0

        while t < duration:
            dt = self.rng.exponential(1.0 / total_rate)
            t += dt
            if t >= duration:
                break
            n_events += 1
            u = self.rng.random() * total_rate
            ref = self._reference_price()

            if u < self.limit_rate:
                side = 'BUY' if self.rng.random() < 0.5 else 'SELL'
                level = min(self.rng.geometric(p=0.4) - 1, self.num_levels - 1)
                offset = (level + 1) * self.tick_size
                price = round(ref - offset, 2) if side == 'BUY' else round(ref + offset, 2)
                size = max(1, int(self.rng.lognormal(np.log(self.mean_limit_size), 0.5)))
                oid = self._new_id()
                self.lob.add_limit_order(oid, side, price, size, t)
                event_log.append((t, 'LIMIT_ADD', side, price, size, oid))

            elif u < self.limit_rate + self.market_rate:
                side = 'BUY' if self.rng.random() < 0.5 else 'SELL'
                size = max(1, int(self.rng.lognormal(np.log(self.mean_market_size), 0.6)))
                self.lob.execute_market_order(side, size, t)
                event_log.append((t, 'MARKET_ORDER', side, None, size, None))

            else:
                if self.lob.order_index:
                    oid = self.rng.choice(list(self.lob.order_index.keys()))
                    side = self.lob.order_index[oid][0]
                    self.lob.cancel_order(oid)
                    event_log.append((t, 'CANCEL', side, None, None, oid))

            if n_events % snapshot_every == 0:
                bb, ba = self.lob.best_bid(), self.lob.best_ask()
                if np.isnan(bb) or np.isnan(ba):
                    continue
                if bb > ba:
                    # Defensive invariant check -- should be structurally
                    # impossible given the crossing-order logic above.
                    warnings.warn(f"Crossed book detected at t={t:.4f}: bid={bb} > ask={ba}")
                bid_lv, bid_sz, ask_lv, ask_sz = self.lob.depth_snapshot(num_levels_snapshot)
                bid_sz_p = bid_sz + [0] * (num_levels_snapshot - len(bid_sz))
                ask_sz_p = ask_sz + [0] * (num_levels_snapshot - len(ask_sz))
                row = {
                    'timestamp': t, 'best_bid': bb, 'best_ask': ba,
                    'mid_price': 0.5 * (bb + ba), 'spread': ba - bb,
                    'bid_depth_total': sum(bid_sz), 'ask_depth_total': sum(ask_sz),
                    'imbalance': (sum(bid_sz) - sum(ask_sz)) / (sum(bid_sz) + sum(ask_sz) + 1e-9),
                }
                for i in range(num_levels_snapshot):
                    row[f'bid_sz_L{i+1}'] = bid_sz_p[i]
                    row[f'ask_sz_L{i+1}'] = ask_sz_p[i]
                snapshots.append(row)

        snap_df = pd.DataFrame(snapshots)
        trades_df = pd.DataFrame(self.lob.trade_log,
                                  columns=['timestamp', 'price', 'size', 'aggressor_side'])
        events_df = pd.DataFrame(event_log,
                                  columns=['timestamp', 'event_type', 'side', 'price', 'size', 'order_id'])
        return snap_df, trades_df, events_df


print("LimitOrderBook and LOBSimulator classes defined.")

"""## 2B. Optional: Load Real LOBSTER Sample Data

[LOBSTER](https://lobsterdata.com) provides free academic sample order-book
data (NASDAQ, a handful of tickers/days) in a standard message-file /
orderbook-file CSV pair. This loader converts that format into the same
`events_df` schema produced by the synthetic simulator above, so every
downstream cell works unchanged regardless of data source.

**Verify column order and the price scale factor against the README bundled
with your specific download** -- LOBSTER's documented format stores prices
multiplied by 10,000 (e.g. `1585000` = \$158.50); minor format variations
have existed across dataset versions.

"""

# ---------------------------------------------------------------------------
# 2B. OPTIONAL LOBSTER LOADER (data source #2 -- requires a manual download)
# ---------------------------------------------------------------------------
def load_lobster_events(message_path, price_scale=10000, side_convention=None):
    """
    Parse a LOBSTER message file into the internal events schema:
    [timestamp, event_type, side, price, size, order_id].

    LOBSTER message file columns (documented format):
        Time, Type, OrderID, Size, Price, Direction
        Type: 1=new limit order, 2=partial cancel, 3=full cancel/delete,
              4=visible execution, 5=hidden execution, 7=trading halt
        Direction: 1=buy limit order resting, -1=sell limit order resting
                   (for executions, this is the resting order's side --
                   the AGGRESSOR side is the opposite sign)

    Parameters
    ----------
    message_path : str, path to the LOBSTER '*_message_*.csv' file
    price_scale   : divisor to convert integer prices to dollars (default 10000)
    side_convention : optional dict to override the default {1: 'BUY', -1: 'SELL'}
                       mapping if your file uses a different convention.

    Returns
    -------
    pandas.DataFrame with columns matching LOBSimulator.run()'s events_df,
    or raises FileNotFoundError with a clear message if the file is missing.
    """
    side_convention = side_convention or {1: 'BUY', -1: 'SELL'}
    try:
        raw = pd.read_csv(message_path, header=None,
                           names=['time', 'type', 'order_id', 'size', 'price', 'direction'])
    except FileNotFoundError:
        raise FileNotFoundError(
            f"LOBSTER message file not found at '{message_path}'. "
            "Download a sample from https://lobsterdata.com and update the path, "
            "or continue using the synthetic simulator in Section 2A."
        )

    raw['price'] = raw['price'] / price_scale
    type_map = {1: 'LIMIT_ADD', 2: 'CANCEL', 3: 'CANCEL', 4: 'MARKET_ORDER', 5: 'MARKET_ORDER'}
    raw = raw[raw['type'].isin(type_map.keys())].copy()
    raw['event_type'] = raw['type'].map(type_map)
    raw['side'] = raw['direction'].map(side_convention)
    # For executions, the resting order's direction is opposite the aggressor;
    # flip side so 'side' consistently reflects the AGGRESSOR for MARKET_ORDER rows.
    is_exec = raw['event_type'] == 'MARKET_ORDER'
    raw.loc[is_exec, 'side'] = raw.loc[is_exec, 'side'].map({'BUY': 'SELL', 'SELL': 'BUY'})

    events = raw.rename(columns={'time': 'timestamp'})[
        ['timestamp', 'event_type', 'side', 'price', 'size', 'order_id']
    ].reset_index(drop=True)
    return events


# Toggle this flag to True and set real file paths to use LOBSTER data instead
# of the synthetic simulator. Everything downstream is unaffected either way.
USE_REAL_LOBSTER_DATA = False
LOBSTER_MESSAGE_PATH = '/content/AAPL_message.csv'  # update if USE_REAL_LOBSTER_DATA=True

if USE_REAL_LOBSTER_DATA:
    try:
        real_events = load_lobster_events(LOBSTER_MESSAGE_PATH)
        print(f"Loaded {len(real_events)} real LOBSTER events.")
    except FileNotFoundError as e:
        print(f"[WARNING] {e}\nFalling back to synthetic data for the rest of this notebook.")
        USE_REAL_LOBSTER_DATA = False
else:
    print("Using synthetic order-flow data (set USE_REAL_LOBSTER_DATA=True to switch).")

"""## 3. Run the Simulation & Reconstruct the Book"""

# ---------------------------------------------------------------------------
# 3. RUN SIMULATION
# ---------------------------------------------------------------------------
sim_cfg = CONFIG['sim']
simulator = LOBSimulator(
    initial_price=sim_cfg['initial_price'], tick_size=sim_cfg['tick_size'],
    num_levels=sim_cfg['num_levels'], limit_rate=sim_cfg['limit_rate'],
    market_rate=sim_cfg['market_rate'], cancel_rate=sim_cfg['cancel_rate'],
    mean_limit_size=sim_cfg['mean_limit_size'], mean_market_size=sim_cfg['mean_market_size'],
    orders_per_level=sim_cfg['orders_per_level'], bootstrap_size=sim_cfg['bootstrap_size'],
    seed=sim_cfg['seed'],
)

snap_df, trades_df, events_df = simulator.run(
    duration=sim_cfg['duration'], num_levels_snapshot=sim_cfg['num_levels_snapshot']
)

print(f"Simulated {len(events_df):,} order-book events over {sim_cfg['duration']:.0f} time units.")
print(f"  -> {len(snap_df):,} book snapshots, {len(trades_df):,} executed trades")
if simulator.lob.unfilled_market_events > 0:
    print(f"  -> Note: {simulator.lob.unfilled_market_events:,} market orders ("
          f"{simulator.lob.unfilled_market_shares:,} shares) exceeded available depth "
          f"and were partially filled -- expected at these order-flow rates given "
          f"the bootstrap depth; adjust CONFIG['sim'] to deepen the book if undesired.")
print("\nEvent type breakdown:")
print(events_df['event_type'].value_counts())
print("\nMid-price summary:")
print(snap_df['mid_price'].describe())
snap_df.head()

"""## 4. Microstructure Metrics

- **Bid-ask spread & order book imbalance** — already computed per snapshot in Section 3.
- **Kyle's (1985) lambda** — price impact per unit of signed order flow, estimated via rolling OLS.
- **Realized volatility vs. Two-Scale Realized Volatility (TSRV)** — the naive "all-tick"
  realized variance is biased upward by bid-ask bounce; Zhang, Mykland & Aït-Sahalia (2005)
  correct this by combining a sparse-sampled ("slow") estimator with the full-tick ("fast")
  estimator.

"""

# ---------------------------------------------------------------------------
# 4. MICROSTRUCTURE METRICS
# ---------------------------------------------------------------------------
def make_regular_price_grid(trades, duration, freq=0.25, price_col='price'):
    """Resample trade prices onto a regular time grid via last-observed-price
    forward fill ('previous tick' scheme) -- the standard approach for
    realized-variance estimation under irregular tick-time sampling."""
    if trades.empty:
        raise ValueError("No trades available to build a price grid.")
    grid = np.arange(0, duration, freq)
    idx = np.searchsorted(trades['timestamp'].values, grid, side='right') - 1
    idx = np.clip(idx, 0, len(trades) - 1)
    return pd.Series(trades[price_col].values[idx], index=grid)


def realized_variance(log_returns):
    return np.sum(log_returns ** 2)


def two_scale_realized_variance(price_series, k_sparse=5):
    """Zhang, Mykland & Ait-Sahalia (2005) two-scale realized volatility (TSRV)."""
    log_p = np.log(price_series.values)
    n = len(log_p) - 1
    if n < k_sparse * 2:
        raise ValueError("Series too short for the requested number of subgrids.")

    all_returns = np.diff(log_p)
    rv_all = realized_variance(all_returns)

    subgrid_rvs, subgrid_sizes = [], []
    for start in range(k_sparse):
        sub = log_p[start::k_sparse]
        if len(sub) < 2:
            continue
        subgrid_rvs.append(realized_variance(np.diff(sub)))
        subgrid_sizes.append(len(sub) - 1)
    rv_avg = np.mean(subgrid_rvs)
    n_bar = np.mean(subgrid_sizes)

    tsrv = rv_avg - (n_bar / n) * rv_all
    return {'rv_all_ticks': rv_all, 'rv_sparse_avg': rv_avg,
            'tsrv': max(tsrv, 0.0), 'n_bar': n_bar, 'n': n}


def rolling_kyle_lambda(trades, snapshots, bucket_size=5.0, window_buckets=20):
    """Kyle's (1985) lambda: regress bucketed mid-price changes on bucketed
    net signed trade volume, delta_mid = lambda * signed_volume + epsilon,
    estimated via rolling OLS."""
    tr = trades.copy()
    tr['signed_size'] = np.where(tr['aggressor_side'] == 'BUY', tr['size'], -tr['size'])
    tr['bucket'] = (tr['timestamp'] // bucket_size).astype(int)
    signed_vol = tr.groupby('bucket')['signed_size'].sum()

    sn = snapshots.copy()
    sn['bucket'] = (sn['timestamp'] // bucket_size).astype(int)
    mid_by_bucket = sn.groupby('bucket')['mid_price'].last()

    df = pd.concat([mid_by_bucket, signed_vol], axis=1).sort_index()
    df.columns = ['mid_price', 'signed_volume']
    df['mid_price'] = df['mid_price'].ffill()
    df['signed_volume'] = df['signed_volume'].fillna(0.0)
    df['delta_mid'] = df['mid_price'].diff()
    df = df.dropna()

    lambdas, r2s, centers = [], [], []
    for i in range(window_buckets, len(df)):
        window = df.iloc[i - window_buckets:i]
        if window['signed_volume'].std() == 0:
            continue
        slope, intercept, r, p, se = stats.linregress(window['signed_volume'], window['delta_mid'])
        lambdas.append(slope)
        r2s.append(r ** 2)
        centers.append(window.index[-1])

    return pd.DataFrame({'bucket': centers, 'kyle_lambda': lambdas, 'r_squared': r2s})


# --- Compute metrics ---
price_grid = make_regular_price_grid(trades_df, sim_cfg['duration'], freq=0.25)
tsrv_full = two_scale_realized_variance(price_grid, k_sparse=5)
kyle_df = rolling_kyle_lambda(trades_df, snap_df, bucket_size=5.0, window_buckets=20)

print("Full-sample realized variance (naive, all ticks):", f"{tsrv_full['rv_all_ticks']:.8f}")
print("Full-sample two-scale realized variance (noise-corrected):", f"{tsrv_full['tsrv']:.8f}")
print(f"Naive RV overstates variance by {(tsrv_full['rv_all_ticks']/max(tsrv_full['tsrv'],1e-12)-1)*100:.1f}% "
      "relative to the noise-corrected estimate.")
print("\nMean spread:", f"{snap_df['spread'].mean():.4f}")
print("Mean |imbalance|:", f"{snap_df['imbalance'].abs().mean():.4f}")
print("Mean Kyle's lambda:", f"{kyle_df['kyle_lambda'].mean():.6f}",
      "| mean R-squared:", f"{kyle_df['r_squared'].mean():.4f}")

"""## 5. Visualizations: Book Dynamics & Microstructure"""

# ---------------------------------------------------------------------------
# 5. VISUALIZATIONS -- BOOK DYNAMICS & MICROSTRUCTURE
# ---------------------------------------------------------------------------
# 5.1 Mid-price and spread
fig, axes = plt.subplots(2, 1, sharex=True)
axes[0].plot(snap_df['timestamp'], snap_df['mid_price'], lw=0.8)
axes[0].set_ylabel('Mid Price'); axes[0].set_title('Reconstructed Mid-Price and Bid-Ask Spread')
axes[1].plot(snap_df['timestamp'], snap_df['spread'], lw=0.8, color='darkorange')
axes[1].set_ylabel('Spread'); axes[1].set_xlabel('Simulated time')
plt.tight_layout(); plt.show()

# 5.2 Order book imbalance
fig, ax = plt.subplots()
ax.plot(snap_df['timestamp'], snap_df['imbalance'], lw=0.6, color='teal')
ax.axhline(0, color='k', lw=0.5)
ax.set_title('Order Book Imbalance Over Time'); ax.set_xlabel('Simulated time'); ax.set_ylabel('Imbalance')
plt.tight_layout(); plt.show()

# 5.3 Depth heatmap (bid/ask size by level over time)
n_frames = min(250, len(snap_df))
resampled = snap_df.iloc[np.linspace(0, len(snap_df) - 1, n_frames).astype(int)]
bid_cols = [c for c in snap_df.columns if c.startswith('bid_sz_L')]
ask_cols = [c for c in snap_df.columns if c.startswith('ask_sz_L')]
bid_matrix = resampled[bid_cols].values.T
ask_matrix = resampled[ask_cols].values.T

fig, axes = plt.subplots(2, 1, sharex=True, figsize=(11, 6))
im0 = axes[0].imshow(bid_matrix, aspect='auto', cmap='Blues', origin='lower',
                      extent=[resampled['timestamp'].iloc[0], resampled['timestamp'].iloc[-1], 1, len(bid_cols)])
axes[0].set_ylabel('Bid Level'); axes[0].set_title('Order Book Depth by Level (darker = more size)')
plt.colorbar(im0, ax=axes[0])
im1 = axes[1].imshow(ask_matrix, aspect='auto', cmap='Reds', origin='lower',
                      extent=[resampled['timestamp'].iloc[0], resampled['timestamp'].iloc[-1], 1, len(ask_cols)])
axes[1].set_ylabel('Ask Level'); axes[1].set_xlabel('Simulated time'); axes[1].set_title('Ask-Side Depth')
plt.colorbar(im1, ax=axes[1])
plt.tight_layout(); plt.show()

# 5.4 Realized variance: naive vs. two-scale (rolling through time)
block = 400
rv_rows = []
for start in range(0, len(price_grid) - block, block // 2):
    seg = price_grid.iloc[start:start + block]
    if len(seg) < 50:
        continue
    res = two_scale_realized_variance(seg, k_sparse=5)
    rv_rows.append({'t_start': seg.index[0], 'rv_all': res['rv_all_ticks'], 'tsrv': res['tsrv']})
rv_df = pd.DataFrame(rv_rows)

fig, ax = plt.subplots()
ax.plot(rv_df['t_start'], rv_df['rv_all'], label='Naive realized variance (all ticks)', lw=1.2)
ax.plot(rv_df['t_start'], rv_df['tsrv'], label='Two-scale realized variance (noise-corrected)', lw=1.2)
ax.set_title('Realized Variance: Naive vs. Microstructure-Noise-Corrected (TSRV)')
ax.set_xlabel('Simulated time'); ax.set_ylabel('Variance per block'); ax.legend()
plt.tight_layout(); plt.show()

# 5.5 Kyle's lambda over time
fig, ax = plt.subplots()
ax.plot(kyle_df['bucket'], kyle_df['kyle_lambda'], lw=1.0, color='purple')
ax.axhline(0, color='k', lw=0.5)
ax.set_title("Rolling Kyle's Lambda (Price Impact per Unit Signed Volume)")
ax.set_xlabel('Time bucket'); ax.set_ylabel('Lambda')
plt.tight_layout(); plt.show()

"""## 6. Almgren-Chriss Optimal Execution

Given a total order size to liquidate over a fixed horizon, the Almgren-Chriss
(2000/2001) framework derives the trading trajectory that minimizes a
mean-variance objective over execution cost: trade too fast and permanent +
temporary market impact erode proceeds; trade too slow and price-path
uncertainty (volatility) increases cost variance. The risk-aversion
parameter **λ** controls where you sit on this trade-off.

"""

# ---------------------------------------------------------------------------
# 6. ALMGREN-CHRISS OPTIMAL EXECUTION
# ---------------------------------------------------------------------------
def almgren_chriss_trajectory(X, T, N, sigma, eta, gamma, lam):
    """
    Almgren & Chriss (2000/2001) optimal execution trajectory.

    Returns (t, x, n): time grid, shares REMAINING at each time point
    (x[0]=X, x[-1]=0), and shares TRADED in each interval.
    lam -> 0 recovers exact TWAP (uniform liquidation).
    """
    if X <= 0 or T <= 0 or N < 1:
        raise ValueError("X, T must be positive and N must be a positive integer.")
    if sigma < 0 or eta <= 0 or gamma < 0 or lam < 0:
        raise ValueError("sigma, gamma, lam must be >= 0 and eta must be > 0.")

    tau = T / N
    eta_tilde = eta - gamma * tau / 2.0
    if eta_tilde <= 0:
        raise ValueError(
            "eta - gamma*tau/2 must be positive; reduce gamma, increase eta, "
            "or use more/shorter trading intervals (smaller tau)."
        )

    t = np.linspace(0, T, N + 1)
    if lam <= 1e-12:
        x = X * (1.0 - t / T)  # risk-neutral limit == TWAP
    else:
        kappa_tilde_sq = lam * sigma ** 2 / eta_tilde
        kappa = np.arccosh(tau ** 2 * kappa_tilde_sq / 2.0 + 1.0) / tau
        x = X * np.sinh(kappa * (T - t)) / np.sinh(kappa * T)

    n = -np.diff(x)
    return t, x, n


def simulate_execution_cost(n_trades, tau, sigma, eta, gamma, arrival_price,
                             n_paths=3000, seed=0):
    """
    Monte Carlo implementation-shortfall simulation under Almgren-Chriss
    price dynamics:
        S_k = S_(k-1) + sigma*sqrt(tau)*Z_k - gamma*n_k          (permanent impact)
        exec_price_k = S_(k-1) - gamma*n_k/2 - eta*(n_k/tau)     (temporary impact)
    Cost = shortfall in dollars relative to arrival price (SELL program).
    """
    rng = np.random.default_rng(seed)
    N = len(n_trades)
    Z = rng.standard_normal((n_paths, N))
    S = np.full(n_paths, arrival_price, dtype=float)
    total_cost = np.zeros(n_paths)
    for k in range(N):
        nk = n_trades[k]
        exec_price = S - gamma * nk / 2.0 - eta * (nk / tau)
        total_cost += nk * (arrival_price - exec_price)
        S = S + sigma * np.sqrt(tau) * Z[:, k] - gamma * nk
    return total_cost


def efficient_frontier(X, T, N, sigma, eta, gamma, arrival_price,
                        lam_grid=None, n_paths=3000, seed=0):
    """Trace expected cost vs. cost variance across a grid of risk-aversion levels."""
    if lam_grid is None:
        lam_grid = np.concatenate(([0.0], np.logspace(-8, -3, 15)))
    rows = []
    for lam in lam_grid:
        t, x, n = almgren_chriss_trajectory(X, T, N, sigma, eta, gamma, lam)
        costs = simulate_execution_cost(n, T / N, sigma, eta, gamma, arrival_price,
                                         n_paths=n_paths, seed=seed)
        rows.append({'lambda': lam, 'expected_cost': costs.mean(),
                     'cost_std': costs.std(), 'cost_variance': costs.var()})
    return pd.DataFrame(rows)


# --- Run ---
ac_cfg = CONFIG['ac']
t_twap, x_twap, n_twap = almgren_chriss_trajectory(
    ac_cfg['X'], ac_cfg['T'], ac_cfg['N'], ac_cfg['sigma'], ac_cfg['eta'], ac_cfg['gamma'], lam=0.0)
t_ac, x_ac, n_ac = almgren_chriss_trajectory(
    ac_cfg['X'], ac_cfg['T'], ac_cfg['N'], ac_cfg['sigma'], ac_cfg['eta'], ac_cfg['gamma'],
    lam=ac_cfg['lam_showcase'])

cost_twap = simulate_execution_cost(n_twap, ac_cfg['T']/ac_cfg['N'], ac_cfg['sigma'],
                                     ac_cfg['eta'], ac_cfg['gamma'], ac_cfg['arrival_price'], seed=1)
cost_ac = simulate_execution_cost(n_ac, ac_cfg['T']/ac_cfg['N'], ac_cfg['sigma'],
                                   ac_cfg['eta'], ac_cfg['gamma'], ac_cfg['arrival_price'], seed=1)

print(f"TWAP:      expected cost = ${cost_twap.mean():,.2f}, cost std = ${cost_twap.std():,.2f}")
print(f"AC-optimal: expected cost = ${cost_ac.mean():,.2f}, cost std = ${cost_ac.std():,.2f}")
print(f"Risk-averse AC trajectory reduces cost STD by "
      f"{(1 - cost_ac.std()/cost_twap.std())*100:.1f}% relative to TWAP, "
      f"at a cost of {(cost_ac.mean()/cost_twap.mean()-1)*100:.1f}% higher expected cost.")

frontier_df = efficient_frontier(ac_cfg['X'], ac_cfg['T'], ac_cfg['N'], ac_cfg['sigma'],
                                  ac_cfg['eta'], ac_cfg['gamma'], ac_cfg['arrival_price'],
                                  n_paths=2000, seed=2)
frontier_df

"""### 6.1 Execution Visualizations"""

# 6.1 Trajectory vs. TWAP
fig, ax = plt.subplots()
ax.plot(t_twap, x_twap, 'o-', label='TWAP (lambda=0)', ms=3)
ax.plot(t_ac, x_ac, 's-', label=f"Risk-averse AC (lambda={ac_cfg['lam_showcase']:.0e})", ms=3)
ax.set_title('Almgren-Chriss Optimal Execution Trajectory vs. TWAP')
ax.set_xlabel('Time'); ax.set_ylabel('Shares remaining'); ax.legend()
plt.tight_layout(); plt.show()

# 6.2 Efficient frontier
fig, ax = plt.subplots()
ax.plot(frontier_df['cost_std'], frontier_df['expected_cost'], 'o-')
ax.set_title('Almgren-Chriss Efficient Frontier: Cost vs. Risk')
ax.set_xlabel('Cost Std. Dev. ($)'); ax.set_ylabel('Expected Cost ($)')
plt.tight_layout(); plt.show()

# 6.3 Cost distribution comparison
fig, ax = plt.subplots()
ax.hist(cost_twap, bins=40, alpha=0.6, label='TWAP', density=True)
ax.hist(cost_ac, bins=40, alpha=0.6, label='AC-optimal', density=True)
ax.set_title('Distribution of Simulated Execution Cost')
ax.set_xlabel('Implementation shortfall ($)'); ax.set_ylabel('Density'); ax.legend()
plt.tight_layout(); plt.show()

"""## 7. Avellaneda-Stoikov Market Making

The Avellaneda-Stoikov (2008) model derives the inventory-aware reservation
price and optimal bid/ask spread for a market maker who wants to earn the
spread while controlling inventory risk, under an assumed exponential
order-arrival intensity `λ(δ) = A·exp(-k·δ)`. We simulate this against a naive
fixed-spread, no-inventory-skew benchmark.

"""

# ---------------------------------------------------------------------------
# 7. AVELLANEDA-STOIKOV MARKET MAKING
# ---------------------------------------------------------------------------
def simulate_avellaneda_stoikov(S0, T, n_steps, sigma, gamma, k, A, seed=0):
    """Avellaneda & Stoikov (2008) inventory-aware market-making simulation."""
    if sigma < 0 or gamma <= 0 or k <= 0 or A <= 0 or n_steps < 1 or T <= 0:
        raise ValueError("Invalid parameter: require sigma>=0, gamma,k,A>0, n_steps>=1, T>0.")

    rng = np.random.default_rng(seed)
    dt = T / n_steps
    s, q, cash = S0, 0, 0.0
    rows = []
    for i in range(n_steps):
        t = i * dt
        time_left = T - t
        r = s - q * gamma * sigma ** 2 * time_left
        spread = gamma * sigma ** 2 * time_left + (2.0 / gamma) * np.log(1.0 + gamma / k)
        bid, ask = r - spread / 2.0, r + spread / 2.0

        delta_b, delta_a = max(s - bid, 0.0), max(ask - s, 0.0)
        p_fill_bid = 1.0 - np.exp(-A * np.exp(-k * delta_b) * dt)
        p_fill_ask = 1.0 - np.exp(-A * np.exp(-k * delta_a) * dt)
        filled_bid = rng.random() < p_fill_bid
        filled_ask = rng.random() < p_fill_ask

        if filled_bid:
            q += 1; cash -= bid
        if filled_ask:
            q -= 1; cash += ask

        rows.append({'time': t, 'mid_price': s, 'reservation_price': r, 'bid': bid, 'ask': ask,
                     'spread': spread, 'inventory': q, 'cash': cash, 'pnl': cash + q * s})
        s = s + sigma * np.sqrt(dt) * rng.standard_normal()
    return pd.DataFrame(rows)


def simulate_naive_market_maker(S0, T, n_steps, sigma, fixed_half_spread, k, A, seed=0):
    """Benchmark: symmetric fixed-spread quoting with NO inventory skew."""
    rng = np.random.default_rng(seed)
    dt = T / n_steps
    s, q, cash = S0, 0, 0.0
    rows = []
    p_fill = 1.0 - np.exp(-A * np.exp(-k * fixed_half_spread) * dt)
    for i in range(n_steps):
        t = i * dt
        bid, ask = s - fixed_half_spread, s + fixed_half_spread
        filled_bid = rng.random() < p_fill
        filled_ask = rng.random() < p_fill
        if filled_bid:
            q += 1; cash -= bid
        if filled_ask:
            q -= 1; cash += ask
        rows.append({'time': t, 'mid_price': s, 'inventory': q, 'cash': cash, 'pnl': cash + q * s})
        s = s + sigma * np.sqrt(dt) * rng.standard_normal()
    return pd.DataFrame(rows)


# --- Run ---
as_cfg = CONFIG['as_mm']
as_df = simulate_avellaneda_stoikov(as_cfg['S0'], as_cfg['T'], as_cfg['n_steps'], as_cfg['sigma'],
                                     as_cfg['gamma_low'], as_cfg['k'], as_cfg['A'], seed=as_cfg['seed'])
as_high_gamma_df = simulate_avellaneda_stoikov(as_cfg['S0'], as_cfg['T'], as_cfg['n_steps'], as_cfg['sigma'],
                                                as_cfg['gamma_high'], as_cfg['k'], as_cfg['A'], seed=as_cfg['seed'])
naive_df = simulate_naive_market_maker(as_cfg['S0'], as_cfg['T'], as_cfg['n_steps'], as_cfg['sigma'],
                                        as_cfg['naive_half_spread'], as_cfg['k'], as_cfg['A'], seed=as_cfg['seed'])

print(f"AS (gamma={as_cfg['gamma_low']}):  final P&L=${as_df['pnl'].iloc[-1]:.2f}, "
      f"max|inventory|={as_df['inventory'].abs().max()}, P&L std=${as_df['pnl'].std():.2f}")
print(f"AS (gamma={as_cfg['gamma_high']}):  final P&L=${as_high_gamma_df['pnl'].iloc[-1]:.2f}, "
      f"max|inventory|={as_high_gamma_df['inventory'].abs().max()}, P&L std=${as_high_gamma_df['pnl'].std():.2f}")
print(f"Naive fixed-spread: final P&L=${naive_df['pnl'].iloc[-1]:.2f}, "
      f"max|inventory|={naive_df['inventory'].abs().max()}, P&L std=${naive_df['pnl'].std():.2f}")

"""### 7.1 Market Making Visualizations"""

fig, axes = plt.subplots(3, 1, sharex=True, figsize=(10, 8))
axes[0].plot(as_df['time'], as_df['mid_price'], lw=0.7, label='Mid price')
axes[0].plot(as_df['time'], as_df['bid'], lw=0.5, alpha=0.6, label='AS bid')
axes[0].plot(as_df['time'], as_df['ask'], lw=0.5, alpha=0.6, label='AS ask')
axes[0].legend(fontsize=8); axes[0].set_ylabel('Price')

axes[1].plot(as_df['time'], as_df['inventory'], label=f"AS inventory (gamma={as_cfg['gamma_low']})", lw=1.0)
axes[1].plot(naive_df['time'], naive_df['inventory'], label='Naive inventory', lw=1.0, alpha=0.7)
axes[1].axhline(0, color='k', lw=0.5); axes[1].legend(fontsize=8); axes[1].set_ylabel('Inventory')

axes[2].plot(as_df['time'], as_df['pnl'], label='AS P&L', lw=1.0)
axes[2].plot(naive_df['time'], naive_df['pnl'], label='Naive P&L', lw=1.0, alpha=0.7)
axes[2].legend(fontsize=8); axes[2].set_ylabel('P&L'); axes[2].set_xlabel('Time')
plt.suptitle('Avellaneda-Stoikov Market Maker vs. Naive Fixed-Spread Benchmark')
plt.tight_layout(); plt.show()

# Inventory-risk sensitivity across risk-aversion levels
gammas = [0.05, 0.1, 0.3, 0.6, 1.0, 1.5]
sens_rows = []
for g in gammas:
    d = simulate_avellaneda_stoikov(as_cfg['S0'], as_cfg['T'], as_cfg['n_steps'], as_cfg['sigma'],
                                     g, as_cfg['k'], as_cfg['A'], seed=as_cfg['seed'])
    sens_rows.append({'gamma': g, 'inventory_std': d['inventory'].std(),
                       'pnl_std': d['pnl'].std(), 'final_pnl': d['pnl'].iloc[-1]})
sens_df = pd.DataFrame(sens_rows)

fig, axes = plt.subplots(1, 2, figsize=(11, 4))
axes[0].plot(sens_df['gamma'], sens_df['inventory_std'], 'o-')
axes[0].set_xlabel('Risk aversion (gamma)'); axes[0].set_ylabel('Inventory Std. Dev.')
axes[0].set_title('Inventory Risk vs. Risk Aversion')
axes[1].plot(sens_df['gamma'], sens_df['pnl_std'], 'o-', color='darkred')
axes[1].set_xlabel('Risk aversion (gamma)'); axes[1].set_ylabel('P&L Std. Dev.')
axes[1].set_title('P&L Volatility vs. Risk Aversion')
plt.tight_layout(); plt.show()
sens_df

"""## 8. Performance Summary Dashboard"""

# ---------------------------------------------------------------------------
# 8. PERFORMANCE SUMMARY DASHBOARD
# ---------------------------------------------------------------------------
summary = pd.DataFrame([
    {'Category': 'Microstructure', 'Metric': 'Mean bid-ask spread', 'Value': f"{snap_df['spread'].mean():.4f}"},
    {'Category': 'Microstructure', 'Metric': 'Market orders exceeding available depth', 'Value':
        f"{simulator.lob.unfilled_market_events:,} of {len(events_df[events_df.event_type=='MARKET_ORDER']):,}"},
    {'Category': 'Microstructure', 'Metric': 'Mean |order book imbalance|', 'Value': f"{snap_df['imbalance'].abs().mean():.4f}"},
    {'Category': 'Microstructure', 'Metric': "Mean Kyle's lambda", 'Value': f"{kyle_df['kyle_lambda'].mean():.6f}"},
    {'Category': 'Microstructure', 'Metric': 'Naive RV / TSRV ratio (noise inflation)', 'Value':
        f"{tsrv_full['rv_all_ticks']/max(tsrv_full['tsrv'],1e-12):.2f}x"},
    {'Category': 'Execution (Almgren-Chriss)', 'Metric': 'TWAP expected cost', 'Value': f"${cost_twap.mean():,.2f}"},
    {'Category': 'Execution (Almgren-Chriss)', 'Metric': 'AC-optimal expected cost', 'Value': f"${cost_ac.mean():,.2f}"},
    {'Category': 'Execution (Almgren-Chriss)', 'Metric': 'TWAP cost std. dev.', 'Value': f"${cost_twap.std():,.2f}"},
    {'Category': 'Execution (Almgren-Chriss)', 'Metric': 'AC-optimal cost std. dev.', 'Value': f"${cost_ac.std():,.2f}"},
    {'Category': 'Market Making (Avellaneda-Stoikov)', 'Metric': f"AS (gamma={as_cfg['gamma_low']}) final P&L", 'Value': f"${as_df['pnl'].iloc[-1]:,.2f}"},
    {'Category': 'Market Making (Avellaneda-Stoikov)', 'Metric': 'AS max |inventory|', 'Value': f"{as_df['inventory'].abs().max()}"},
    {'Category': 'Market Making (Avellaneda-Stoikov)', 'Metric': 'Naive max |inventory|', 'Value': f"{naive_df['inventory'].abs().max()}"},
    {'Category': 'Market Making (Avellaneda-Stoikov)', 'Metric': 'AS P&L std. dev.', 'Value': f"${as_df['pnl'].std():,.2f}"},
    {'Category': 'Market Making (Avellaneda-Stoikov)', 'Metric': 'Naive P&L std. dev.', 'Value': f"${naive_df['pnl'].std():,.2f}"},
])
summary

"""## 9. Conclusion & Potential Upgrades

This notebook implemented an end-to-end institutional-grade microstructure
and execution research pipeline: order-book reconstruction under
price-time priority, noise-robust volatility estimation, price-impact
estimation, and two canonical execution/market-making models validated
against known theoretical limits (TWAP recovery at λ=0; inventory-variance
reduction with risk aversion).

**Potential upgrades:**
- Replace the synthetic simulator with real LOBSTER or exchange-provided tick data.
- Extend Almgren-Chriss to a multi-asset execution program with cross-impact.
- Add adverse-selection-aware market making (e.g., Guéant-Lehalle-Fernandez-Tapia model).
- Wrap Sections 3-8 into a Streamlit or Plotly Dash app for a live interactive dashboard.
- Backtest the Avellaneda-Stoikov quotes against the actual reconstructed
  order book from Section 3 rather than a fresh simulated price path.

"""